---

- name: install wget
  win_command: powershell.exe choco install wget -y

- name: install unzip
  win_command: powershell.exe choco install unzip -y

- name: stop node.exe 
  win_command: powershell.exe "taskkill /IM node.exe /F"
  ignore_errors: yes

- name: delete apache
  win_file: 
     path: C:\Users\zippyops\Downloads\node-v10.15.3-win-x64.zip
     state: absent

- name: download apache
  win_command: powershell.exe C:\ProgramData\chocolatey\bin\wget -P C:\Users\zippyops\Downloads https://nodejs.org/dist/v10.15.3/node-v10.15.3-win-x64.zip 

- name: rmdir httpd
  win_file: 
     path: C:\node-v10.15.3-win-x64 
     state: absent

- name: unzip apache
  win_command: powershell.exe C:\ProgramData\chocolatey\bin\unzip C:\Users\zippyops\Downloads\node-v10.15.3-win-x64.zip -d C:\

- name: Copy node-js-sample to nodes
  win_copy: src=/etc/ansible/nodejs/files/node-js-sample dest=C:\

- name: execute index.js 
  win_command: powershell.exe "cd C:\node-js-sample\; C:\node-v10.15.3-win-x64\node index.js"

