
---
- name: Update packages (this is equivalent to yum update -y)
  yum: name=* state=latest

- name: Install dependencies for WordPress
  yum: name={{ item }} state=present
  with_items:
        - httpd
        - mariadb-server 
        - mariadb
        - php 
        - php-mysql
        - MySQL-python

- name: Ensure MariaDB is running (and enable it at boot)
  service: name=mariadb state=started enabled=yes

- name: Copy .my.cnf to nodes
  copy: src=/etc/ansible/php/.my.cnf dest=/root/.my.cnf

- name: Create MariaDB database
  mysql_db: name=test state=present

- name: Create MariaDB username and password
  mysql_user:
        login_user=root
        name=root
        priv=*.*:ALL

# tasks file for wp-install-config
- name: Create directory to download WordPress
  command: mkdir -p /opt/source/wordpress

- name: Download WordPress
  get_url: url=https://www.wordpress.org/latest.tar.gz dest=/opt/source/wordpress/wordpress.tar.gz validate_certs=no

- name: Extract WordPress
  command: "tar xzf /opt/source/wordpress/wordpress.tar.gz -C /var/www/html --strip-components 1"

- name: Send config file
  copy: src=/etc/ansible/php/wp-config-sample.php dest=/var/www/html/wp-config.php mode=0644
- name: Ensure httpd is running (and enable it at boot)
  service: name=httpd state=restarted enabled=yes

